version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/kijiji_clone
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runs: ubuntu
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ubuntu